### ISSUE TITLE
Button "Run in launched JVM" appears only for Maven based projects

### ISSUE THREAD

**Issue by dmitrykoryanov** [wrike/sprinter-idea-plugin#1] opened 2023-08-31 07:06 UTC
Button "Run in launched JVM" appears only for Maven based projects, but doesn't appear for Gradle projects (Groovy or Kotlin), The steps to repoduce are very simple - generate an empty Spring Boot project [start.spring,io](https://start.spring.io/) using different options (Gradle - Groovy, Gradle - Kotlin, Maven).

**Comment by Mugenor** [comment] 2023-08-31 08:37
Hi
Yes, it's known issue
There is a workaround: in Settings -> Build, Execution, Deployment -> Build Tools -> Gradle change option "Run test using:" to IntelliJ IDEA.

The problem is that in case gradle is selected there, IDEA will run tests using `gradle test` and I didn't find a way to override test runner to a custom one for such case, meaning that I can't support plugin's functionality.
If you know the way to do it, please, share, I'll try to implement it.

**Comment by dmitrykoryanov** [comment] 2023-08-31 15:38
Hi, many thanks for the quick reply - it helped.. Now I can run certain integration tests and can clearly see, that they are being executed 2-4 times faster with this plugin. Next question would be, is it possible to modify edit configuration in such way, that I could apply "Run in launched JVM"" to a  whole set of tests, not only to a certain test calss/method?

**Comment by Mugenor** [comment] 2023-09-01 13:42
You can either create a template for plugins configuration (SharedJvmForTest) or template for configuration for the framework you are using (JUnit/TestNG). In latter case the plugin by default will inherit configurations from the framework's configuration template. You can change this behaviour in settings (Settings -> Tools -> Sprinter Settings -> 3 checkboxes under "Inherit Configuration Values From Test Configuration")
I hope it solves your problem :)

**Comment by Mugenor** [comment] 2023-09-11 14:20
I'll close the issue since there was no reply for a long time, but feel free to reopen it to ask more questions.

**Closed as completed by Mugenor** 2023-09-11 14:20 UTC
